"""Namespaced audit event names owned by the GTD feature."""

from enum import StrEnum


class EventType(StrEnum):
    CAPTURED = "gtd.inbox.captured"
    CLARIFIED = "gtd.inbox.clarified"
    TASK_STARTED = "gtd.task.started"
    TASK_STOPPED = "gtd.task.stopped"
    TASK_COMPLETED = "gtd.task.completed"
    TASK_DEFINED = "gtd.task.defined"
    TASK_CONDITION_CHECKED = "gtd.task.condition.checked"
    TASK_ASSURANCE_REVIEWED = "gtd.task.assurance.reviewed"
    TASK_BLOCKED = "gtd.task.blocked"
    TASK_DEFERRED = "gtd.task.deferred"
    TASK_DELEGATED = "gtd.task.delegated"
    TASK_DUE_SET = "gtd.task.due.set"
    TASK_ESCALATED = "gtd.task.escalated"
    TASK_ESTIMATE_UPDATED = "gtd.task.estimate.updated"
    TASK_LINKED = "gtd.task.linked"
    TASK_PARENT_SET = "gtd.task.parent.set"
    TASK_REOPENED = "gtd.task.reopened"
    TASK_RESPONSE_RECORDED = "gtd.task.response.recorded"
    TASK_RECURRENCE_CREATED = "gtd.task.recurrence.created"
    TASK_RECURRENCE_SET = "gtd.task.recurrence.set"
    TASK_WORK_LOG_CORRECTED = "gtd.task.work.corrected"
    TASK_WORK_LOGGED = "gtd.task.work.logged"
    TASK_READY = "gtd.task.ready"
    TASK_SCHEDULED = "gtd.task.scheduled"
    TASK_SWITCHED = "gtd.task.switched"
    TASK_UNBLOCKED = "gtd.task.unblocked"
    TASK_WAITING_FOLLOWED_UP = "gtd.task.waiting.followed_up"
    TASK_WAITING_RESOLVED = "gtd.task.waiting.resolved"
    PROJECT_COMPLETED = "gtd.project.completed"
    REVIEW_STARTED = "gtd.review.started"
    REVIEW_STEP_CHECKED = "gtd.review.step.checked"
    REVIEW_COMPLETED = "gtd.review.completed"
